---
- name: BENCHMARK
  hosts: routers
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Setup | Creating save file
      copy:
        content: ""
        dest: "/etc/ansible/logs/RunVars.txt"

    - name: Setup | Creating router save file
      copy:
        content: ""
        dest: "/etc/ansible/logs/{{ inventory_hostname }}.txt"

    - name: run the command 'show interfaces'
      ios_command:
        commands: show interfaces
      register: Output_Int

    - name: save interface file
      copy:
        content: "{{ Output_Int.stdout }}"
        dest: "/etc/ansible/logs/int_{{ inventory_hostname }}.txt"

    - name: Filtering out MTU values
      become_user: root
      shell: "python3 /etc/ansible/filters/filter_mtu.py --hostname {{ inventory_hostname }}"
      register: mtu_out

    - set_fact:
       MTUValue: "{{ mtu_out.stdout }}"

    - name: Print Data
      debug: var=MTUValue

    - name: ping 10 to host
      ios_command:
        commands: ping 192.168.0.2 repeat 10
      register: Output_Ping

    - name: save file
      copy:
        content: "{{ Output_Ping.stdout }}"
        dest: "/etc/ansible/logs/ping_{{ inventory_hostname }}.txt"

    - name: Filtering out PING values
      become_user: root
      shell: "python3 /etc/ansible/filters/filter_ping.py --hostname {{ inventory_hostname }}"
      register: ping_out

    - set_fact:
       PINGValue: "{{ ping_out.stdout }}"

    - name: Debug PING
      debug: var=PINGValue

    - name: Save Ping data
      lineinfile:
        path: /etc/ansible/logs/RunVars.txt
        line: "{{ inventory_hostname }} = {{ PINGValue }}"

    - name: Format results
      template:
        src: "/etc/ansible/templates/results.j2"
        dest: "/etc/ansible/benchmarks/{{ inventory_hostname }}.txt"

    - name: Combine network to one file
      become_user: root
      shell: "python3 /etc/ansible/filters/combine_devices.py"
